

compile:
	c++ -o prosjekt1.exe  prosjekt1.cpp
	c++ -o prosjekt1c.exe  prosjekt1c.cpp


runb:
	clear
	c++ -o prosjekt1.exe  prosjekt1.cpp
	./prosjekt1.exe resultat v_og_x.txt 1
	python plott.py
	python relativerror.py
runc:
	clear
	c++ -o prosjekt1c.exe  prosjekt1c.cpp
	./prosjekt1c.exe 1

rune:
	clear
	c++ -o prosjekt1e.exe  prosjekt1e.cpp -larmadillo
	./prosjekt1e.exe 1

#clean:
#	rm prosjekt1.exe

#clear_screen:
#	clear


#all: clear_screen compile
