

run_jacobi:
	clear
	c++ -o prosjekt2.exe  prosjekt2.cpp
	./prosjekt2.exe 10 plott_egenvektor.txt
	python plott_egenvektor.py


run_armendillo:
	clear
	c++ -o armendillo_eig.exe  armendillo_eig.cpp -larmadillo -llapack -lblas
	./armendillo_eig.exe 10


run_elektroner:
	clear
	c++ -o quantum_dots.exe  quantum_dots.cpp
	./quantum_dots.exe 100
