
run:
	clear
	c++ -o solarsystem.exe  solarsystem.cpp -larmadillo
	./solarsystem.exe verdier.py 10
	python plott.py


runb:
	clear
	c++ -o b.exe  b.cpp -larmadillo
	./b.exe euler.txt verlet.txt
	python plotteuler.py

runFrank:
	clear
	c++ -o Frank.exe  Frank.cpp -larmadillo
	./Frank.exe Euler Veilet
	python plottFrank.py
